language: python
python:
  - "2.7"

install:
    - travis_retry pip install tox==1.8
script:
    - tox -e py27
after_success:
    - tox -e py27-coveralls

# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
