dist: trusty
sudo: required

language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env:
        TOXENV=py36
        JDK_SWITCH=openjdk7
    - python: 3.7
      # from https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442
      dist: xenial
      env:
        TOXENV=py37
        JDK_SWITCH=openjdk8

env:
  - SKIP_NETWORK_TESTS=0

install:
    - travis_retry pip install tox
    - jdk_switcher use "${JDK_SWITCH}"
script:
    - java -version
    - TOX_ENVIRONMENT="py${TRAVIS_PYTHON_VERSION//./}"
    - tox -e "$TOX_ENVIRONMENT"
after_success:
    - if [[ $TOX_ENVIRONMENT == 'py36' ]] ; then tox -e py36-coveralls; else echo "No coverage to do"; fi
